{ pkgs, ... }: {
  environment.systemPackages = with pkgs; [
    neovim
    btop
    gnupg
    interception-tools
    gemini-cli
    wget
    libayatana-appindicator
    cliphist
    unrar
    polkit_gnome
    nekoray
    osu-lazer
    swaylock
    keybinder3
    mako
    apple-cursor
    firefox-devedition
    fd
    fzf
    wl-clipboard
    pipewire
    ripgrep
    pulseaudio
    qbittorrent
    zathura
    libreoffice
    syncthing
    xdg-utils
    bluez
    fzf
    firefox
    gtk2
    playerctl
    pnpm
    bluetuith
    kitty
    mesa
    libdrm
    ffmpeg
    unzip
    eza
    atool
    bat
    typescript
    nodejs_22
    yazi
    brave
    chromium
    tree
    steam
    maple-mono.CN
    maple-mono."CN-unhinted"
    maple-mono.NF
    maple-mono."NF-CN"
    gcc
    p7zip
    git
    alsa-utils
    fishPlugins.fish-you-should-use
    fishPlugins.plugin-git
    fishPlugins.done
    fishPlugins.autopair
    gtk3
    libnotify
    xorg.xrandr
    obsidian
    ayugram-desktop
    nerd-fonts._0xproto
  ];
  environment.shells = with pkgs; [ fish ];
}
