{
  imports = [
    ./nixpkgs.nix
    ./docker.nix
    ./waydroid.nix
    ./openssh.nix
    ./nix-ld.nix
    ./znix
    ./packages.nix
    ./pipewire.nix
    ./graphics.nix
    ./bluetooth.nix
    ./users
    ./timezone.nix
    ./networking.nix
    ./boot.nix
    ./flatpak.nix
  ];
}
